framework:
    messenger:
        transports:
            # folosim message transporter doctrine
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
        
        routing:
            'App\Message\UpdateAffectiveItemsAnalysisRating': async
            'App\Message\AddAffectiveItemsAnalysisRating': async
            'App\Message\DeleteAffectiveItemsAnalysisRating': async
