framework:
    messenger:
        transports:
            # DSN-ul va indica cum și unde să fie trimise mesajele pentru procesare asincronă.
            # folosim message transporter doctrine
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
        
        # orice mesaj de aceste tipuri va fi gestionat asincron
        routing:
            'App\Message\ModifyAffectiveItemsAnalysisRatingInterface': async
